{
  "hash": "0cd2de770af5e01b4ae5f24de8e1e3fd",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Exploratory Spatial Analysis of Regional Total Fertility \nRates in South Korea: Part 1\"\ndescription: \"Using Geographically Weighted Regression and \nGeographical Random Forests\"\nauthor:\n  - name: Woohyung Kim\n    url: https://geowhk.github.io/\n    affiliation: GIS Lab, Department of Geography Education at Seoul National University\n    affiliation-url: https://geoedu.snu.ac.kr/ \ndate: 07-03-2024\ncategories: [R, Machine Learning, Spatial Analysis] # self-defined categories\ncitation: \n  url: https://geowhk.github.io/posts/2024-07-03-first-blog/ \nimage: preview-image.png\ndraft: false # setting this to `true` will prevent your post from appearing on your listing page until you're ready!\n---\n\n\nMy first semester as a graduate student has finally ended{{< fa face-grin-stars >}} This semester, I took a Spatial Data Mining class and wrote a term paper using GWR(Geographically Weighted Regression) and GRF(Geographic Random Forests). I want to share what I did with this blog post.\n\nMy goal was to see if there is spatial non-stationarity in the regional total fertility rate in South Korea. I set the Sigungu level as the study scale. Sigungu is the second-largest administrative region in South Korea.\n\n::: {.callout-note collapse=\"true\"}\n## What is spatial non-stationarity?\n\nSpatial non-stationarity means that the relationship between variables is spatially varying.\n:::\n\n\n::: {.cell}\n\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-2-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nA dependent variable is the **Total fertility rate**. I used the following variables as independent variables:\n\n-   **Population density**(*pop_den*)\n\n-   **Average birth incentive per capita**(*incentive*)\n\n-   **The proportion of women with college degrees or higher**(*grad*)\n\n-   **The age of first marriage for women**(*first*)\n\n-   **The number of childcare facilities per 1,000 children under 6**(*under6*)\n\n-   **Gross regional domestic product per capita**(*grdpPercap*)\n\nall the variables are based on data from the year 2020.\n\n<br/>\n\n## Global analysis\n\n### Correlation analysis\n\nBefore analyzing the variables locally, I conducted some global analysis.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(readxl)\nTFR <- read_excel(\"TFR2020.xlsx\")\nstr(TFR)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [251 × 9] (S3: tbl_df/tbl/data.frame)\n $ sgg       : num [1:251] 0 11010 11020 11030 11040 ...\n $ name      : chr [1:251] \"전국\" \"종로구\" \"중구\" \"용산구\" ...\n $ tfr       : num [1:251] 0.837 0.522 0.688 0.634 0.783 0.527 0.699 0.66 0.676 0.55 ...\n $ pop_den   : num [1:251] 516 6306 12887 10318 17358 ...\n $ incentive : num [1:251] 1.01 0.677 0.605 0.532 0.374 ...\n $ grad      : num [1:251] 20.6 41.1 36.3 46.4 40 ...\n $ first     : num [1:251] 30.7 32 32.1 32.2 31.6 ...\n $ under6    : num [1:251] 12.7 15.6 13.4 11 11.9 ...\n $ grdpPercap: num [1:251] 41.1 224 435.5 56.8 42.6 ...\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(TFR)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      sgg            name                tfr            pop_den        \n Min.   :    0   Length:251         Min.   :0.4450   Min.   :   18.37  \n 1st Qu.:24035   Class :character   1st Qu.:0.7845   1st Qu.:  103.45  \n Median :32310   Mode  :character   Median :0.9240   Median :  624.14  \n Mean   :29749                      Mean   :0.9548   Mean   : 3850.92  \n 3rd Qu.:36325                      3rd Qu.:1.0645   3rd Qu.: 5884.99  \n Max.   :39020                      Max.   :2.4550   Max.   :25143.33  \n   incentive           grad           first           under6      \n Min.   :0.0000   Min.   : 6.51   Min.   :28.34   Min.   : 3.831  \n 1st Qu.:0.4314   1st Qu.:12.51   1st Qu.:30.21   1st Qu.:10.662  \n Median :0.7860   Median :18.76   Median :30.66   Median :12.702  \n Mean   :1.0105   Mean   :20.61   Mean   :30.68   Mean   :12.899  \n 3rd Qu.:1.3544   3rd Qu.:25.34   3rd Qu.:31.09   3rd Qu.:14.767  \n Max.   :4.9820   Max.   :59.96   Max.   :32.49   Max.   :27.231  \n   grdpPercap    \n Min.   : 10.82  \n 1st Qu.: 26.04  \n Median : 32.87  \n Mean   : 39.34  \n 3rd Qu.: 41.70  \n Max.   :435.52  \n```\n\n\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(GGally)\nTFR |> \n  select(tfr, pop_den, incentive, grad, first, under6, grdpPercap) |> \n  ggpairs()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nI found that some variables have skewed distributions, so I decided to apply log transformation to those variables.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nTFR_log <- TFR |> \n  mutate(\n    tfr_log = log(tfr),\n    popden_log = log(pop_den),\n    incentive_log = log(incentive + 1),\n    grad_log = log(grad),\n    grdpPercap_log = log(grdpPercap)\n  ) |> \n  select(-c(tfr, grad, grdpPercap, pop_den, incentive))\n\nTFR_log |> \n  select(-c(sgg, name)) |> \n  relocate(tfr_log, popden_log, incentive_log, grad_log, first, under6, grdpPercap_log) |> \n  ggpairs()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nNow the distributions look much better than before. In this correlation matrix, I found that there are some significant correlations between independent variables. This is called multicollinearity, and in the regression analysis, it negatively affect the results. Researchers usually address this issue by removing some variables or conducting dimension reduction techniques such as Principle Component Analysis (PCA). However, in my case, **\"global correlations\"** between independent variables do not necessarily imply **\"local correlations\"**. Therefore, I decided to use all the variables as they are.\n\n### Regression Analysis\n\nI also conducted an Ordinary Least Squares Regression (OLS) to examine the relationship between dependent and independent variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTFR_log_sgg <- TFR_log[-1, ] # first row contains the value of the whole country.\nmodel_log <- lm(tfr_log ~ \n                  popden_log + incentive_log + grad_log + first + under6 + grdpPercap_log,\n                data = TFR_log_sgg)\nsummary(model_log)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = tfr_log ~ popden_log + incentive_log + grad_log + \n    first + under6 + grdpPercap_log, data = TFR_log_sgg)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.43705 -0.10125  0.00607  0.09694  0.58561 \n\nCoefficients:\n                 Estimate Std. Error t value             Pr(>|t|)    \n(Intercept)     2.7979081  0.5178115   5.403          0.000000156 ***\npopden_log     -0.0847490  0.0085770  -9.881 < 0.0000000000000002 ***\nincentive_log   0.1072175  0.0333750   3.213              0.00149 ** \ngrad_log        0.0805996  0.0374403   2.153              0.03232 *  \nfirst          -0.0806301  0.0168346  -4.790          0.000002909 ***\nunder6         -0.0116743  0.0034761  -3.358              0.00091 ***\ngrdpPercap_log  0.0005006  0.0221743   0.023              0.98201    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.162 on 243 degrees of freedom\nMultiple R-squared:  0.6221,\tAdjusted R-squared:  0.6128 \nF-statistic: 66.68 on 6 and 243 DF,  p-value: < 0.00000000000000022\n```\n\n\n:::\n:::\n\n\nThree variables (*popden_log, first, under6*) showed the most significance, followed by *incentive_log* and *grad_log*. *grdpPercap_log* showed no significance. The coefficient of determination ($R^2$) was 0.6221, and the adjusted $R^2$ was 0.6128. I considered this model sufficient to explain the relationship.\n\nUsing the result of the regression analysis, I evaluated the model's performance with Root Mean Square Error (RMSE) and Mean Absolute Error (MAE).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobs_val <- TFR_log_sgg$tfr_log\npred_val_OLS <- model_log$fitted.values\nres_OLS <- obs_val - pred_val_OLS\n\nrmse_OLS <- sqrt(mean(res_OLS^2))\nrmse_OLS\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1597133\n```\n\n\n:::\n\n```{.r .cell-code}\nmae_OLS <- mean(abs(res_OLS))\nmae_OLS\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1243839\n```\n\n\n:::\n:::\n\n\n### Spatial visualization\n\nBefore moving on to the local analysis, I wanted to see the distribution of the variables. So, I created choropleth maps for all the variables. To make a map, I joined table data containing the variables with the spatial data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(sf)\n\nsgg <- st_read(\"bnd_sigungu_00_2020_2020_4Q.shp\", quiet = TRUE)\nsummary(sgg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  BASE_DATE          SIGUNGU_CD         SIGUNGU_NM             pop        \n Length:250         Length:250         Length:250         Min.   :  8444  \n Class :character   Class :character   Class :character   1st Qu.: 57312  \n Mode  :character   Mode  :character   Mode  :character   Median :174506  \n                                                          Mean   :207317  \n                                                          3rd Qu.:314999  \n                                                          Max.   :880859  \n    pop_den                  geometry  \n Min.   :   18.37   MULTIPOLYGON :250  \n 1st Qu.:  103.13   epsg:NA      :  0  \n Median :  625.48   +proj=tmer...:  0  \n Mean   : 3864.26                      \n 3rd Qu.: 5929.76                      \n Max.   :25143.33                      \n```\n\n\n:::\n\n```{.r .cell-code}\nsgg$SIGUNGU_CD <- as.integer(sgg$SIGUNGU_CD) # convert \"SIGUNGU_CD\" in \"sgg\" as integer\nsgg_TFR <- sgg |> # join table data with spatial data\n  left_join(TFR_log, join_by(SIGUNGU_CD == sgg)) |> \n  select(-c(pop, pop_den))\nsummary(sgg_TFR)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  BASE_DATE           SIGUNGU_CD     SIGUNGU_NM            name          \n Length:250         Min.   :11010   Length:250         Length:250        \n Class :character   1st Qu.:24043   Class :character   Class :character  \n Mode  :character   Median :32315   Mode  :character   Mode  :character  \n                    Mean   :29868                                        \n                    3rd Qu.:36328                                        \n                    Max.   :39020                                        \n     first           under6          tfr_log           popden_log    \n Min.   :28.34   Min.   : 3.831   Min.   :-0.80968   Min.   : 2.911  \n 1st Qu.:30.21   1st Qu.:10.660   1st Qu.:-0.24303   1st Qu.: 4.636  \n Median :30.66   Median :12.673   Median :-0.07850   Median : 6.439  \n Mean   :30.68   Mean   :12.900   Mean   :-0.08017   Mean   : 6.574  \n 3rd Qu.:31.09   3rd Qu.:14.771   3rd Qu.: 0.06321   3rd Qu.: 8.688  \n Max.   :32.49   Max.   :27.231   Max.   : 0.89813   Max.   :10.132  \n incentive_log       grad_log     grdpPercap_log           geometry  \n Min.   :0.0000   Min.   :1.873   Min.   :2.381   MULTIPOLYGON :250  \n 1st Qu.:0.3586   1st Qu.:2.524   1st Qu.:3.258   epsg:NA      :  0  \n Median :0.5798   Median :2.930   Median :3.493   +proj=tmer...:  0  \n Mean   :0.6271   Mean   :2.910   Mean   :3.523                      \n 3rd Qu.:0.8566   3rd Qu.:3.233   3rd Qu.:3.732                      \n Max.   :1.7888   Max.   :4.094   Max.   :6.077                      \n```\n\n\n:::\n:::\n\n\nI used \"sido\" data for better visualization. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tmap)\nsido.shp <- st_read(\"SIDO_2021_gen.shp\", quiet = TRUE) # sido is the largest administrative region in South Korea\ntm_shape(sgg_TFR) +\n  tm_polygons(\"tfr_log\", style = \"jenks\", palette = \"-PuOr\", border.col = \"gray20\", lwd = 1,\n              title = \"Total Fertility Rate(2020)\",\n              midpoint = 0\n              )+\n  tm_shape(sido.shp) +\n  tm_borders(col = \"black\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nI also made maps for the independent variables using a self-made function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvar_mapping <- function(value, title) {\n  tm_shape(sgg_TFR) +\n    tm_polygons(value, style = \"jenks\", palette = \"BuPu\", border.col = \"gray20\", lwd = 1,\n                title = title) +\n    tm_shape(sido.shp) +\n    tm_borders(col = \"black\", lwd =2)\n}\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmap1 <- var_mapping(\"popden_log\", \"Population Density(2020)\")\nmap2 <- var_mapping(\"incentive_log\", \"Birth Incentive(2020)\")\nmap3 <- var_mapping(\"grad_log\", \"Proportion of Women with College Degree of Higher(2020)\")\nmap4 <- var_mapping(\"first\", \"Age of First Marriage for Women(2020)\")\nmap5 <- var_mapping(\"under6\", \"Number of Childcare Facilities per 1,000 under 6(2020)\")\nmap6 <- var_mapping(\"grdpPercap_log\", \"GRDP per Capita(2020)\")\n\ntmap_arrange(map1, map2, map3, map4, map5, map6, ncol = 2, nrow = 3)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-1.png){fig-align='center' width=768}\n:::\n:::\n\n\nGWR and GRF will be introduced in the following posts.\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}